### ISSUE TITLE
libboost_python36.so.1.67.0: cannot open shared object file

### ISSUE THREAD

**Issue by Pupo1** [mkeeter/antimony#210]
Hello, 

on Debian 10 I get

`antimony: error while loading shared libraries: libboost_python36.so.1.67.0: cannot open shared object file: No such file or directory
`

Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

regards, Pupo

**Comment by mkeeter** [comment]
What bindings to boost::python3 have you installed?

Last time I checked, they were part of `libboost-all-dev`, but that may not be true anymore – if that's not the case, please open a PR against [`BUILDING.md`](https://github.com/mkeeter/antimony/blob/develop/BUILDING.md).

**Comment by Pupo1** [comment]
Sorry, I have no idea how I check this. What command should I use to check the python3 binding?

**Comment by mkeeter** [comment]
I can't debug your specific Linux system, but try looking around in `/usr/lib`, `/usr/local/lib`, etc, for something that looks like `libboost_python.*`.

**Comment by Pupo1** [comment]
Thank you for the hint. What do you mean with PR, a pull request?
I installed libboost-all-dev, and find the following files looking similar to what you said:
./lib/x86_64-linux-gnu/libboost_python3-py37.so
./lib/x86_64-linux-gnu/libboost_mpi_python37.so.1.67.0
./lib/x86_64-linux-gnu/libboost_mpi_python3-py37.a
./lib/x86_64-linux-gnu/libboost_python37.a
./lib/x86_64-linux-gnu/libboost_mpi_python3-py37.so
./lib/x86_64-linux-gnu/libboost_python37.so.1.67.0
./lib/x86_64-linux-gnu/libboost_python3-py37.a

I don't know how to write a pull request, because I never did it... :-(

Best regards, Bernd

**Comment by orthzar** [comment]
Bernd,

I had the exact same issue on Debian 11 (Bullseye).  However, Antimony is now working for me after a recent update.

From the Debian [patches list](https://sources.debian.org/patches/antimony/), 0.9.3-1.1 resolves the issue.  Debian 11 and Sid have that patch, but Debian 10 (Buster) does not.

Your options are:

- Upgrade to Debian 11;
- Add Debian 11 to your repository sources list and only upgrade Antimony; or
- Politely ask [Tiago](https://qa.debian.org/developer.php?login=tiago%40debian.org) to get the 0.9.3-1.1 patch added to Debian 10.

Regards,
orthzar


P.S.  If Tiago sees this: thanks!  I can now proceed with a project that I've been putting off.

**Comment by mkeeter** [comment]
Great, I'm going to close this issue as it's been resolved in newer versions of Debian.

**Comment by Pupo1** [comment]
I still wanted to say thank you. to orthzar. I will just upgrade to Debian 11.

**Comment by ceremcem** [comment]
Anyone has a ready-to-apply solution for Debian Buster? Can we download current package and apply that patch manually, and then `apt install antimony-patched.deb`?

**Comment by ceremcem** [comment]
FYI: Upgrading to Debian 10 was not an option to me. I followed the following path instead: 

1. Create an LXC container: 

       $ sudo lxc-create -n antimony -t debian -B btrfs -- -r bullseye --packages xbase-clients nano sudo
       $ sudo lxc-attach -n antimony
       antimony:~# adduser myuser

2. Install Antimony via package manager:
  
       antimony:~# apt-get install antimony

3. Run Antimony over ssh: 

       ssh -X myuser@ip-of-lxc-container antimony

**Comment by nerdCopter** [comment]
if only `Antimony` came in .AppImage :thinking:  ...
same boat, Debian 10 Stable + buster-backports, still an issue.
